spring.application.name=JPA-01-E-CommerceOrderTrackingSystem

# =====================================================================
# JDBC URL for the database (replace localhost, port, and db_name)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=springuser
spring.datasource.password=practice
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# JDBC Driver class name (Optional for newer Spring Boot versions, as it auto-detects)

# =====================================================================
# Hibernate / JPA Settings
# =====================================================================
# SQL Dialect allows Hibernate to optimize generated SQL for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# DDL Auto: controls how database tables are created or updated (none, validate, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=update

# Enable logging of SQL statements to the console
spring.jpa.show-sql=true

# Format the logged SQL statements to make them readable
spring.jpa.properties.hibernate.format_sql=true